name: "Configuration Fetch Action"
description: "Fetch AWS AppConfig configuration files"
author: "Juan Valdivia"
inputs:
  appName:
    required: true
    description: "AWS AppConfig application name input"
  profileName:
    required: true
    description: "AWS Appconfig profile input"
  env: 
    required: true
    description: "AWS AppConfig environment name"
  region: 
    required: true
    description: "AWS Region"

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash

